option( PLATOMAIN     "Flag to turn on compilation of PlatoMain"           OFF )
option( PLATOSTATICS  "Flag to turn on compilation of Statics performer"   OFF )
option( SALINAS       "Flag to turn on testing of Salinas performer"       OFF )
option( ALBANY        "Flag to turn on testing of Albany performer"        OFF )
option( ANALYZE       "Flag to turn on testing of Plato Analyze performer" OFF )
option( REGRESSION    "Flag to create regression test suite"               OFF )
option( UNIT_TESTING  "Flag to turn on unit testing"                       OFF )
option( ENABLE_ISO    "Flag to turn on iso extraction"                     OFF )
option( STK_ENABLED   "Flag to indicate STK is available"                  OFF )
option( GEOMETRY      "Flag to turn on Plato Geometry"                     OFF )
option( EXPY          "Build exodus python API"                            OFF )
option( SEACAS        "Seacas tools"                                       OFF )
option( AMFILTER_ENABLED        "Build with AMFilter and ArborX"           OFF )

option(PLATO_ENABLE_SERVICES_PYTHON "Enable the Plato Python interface"    OFF)
