include(./cmake/plato_functional_setup.cmake)
include(./cmake/clang_tidy_setup.cmake)
include( ./cmake/copy_test_utility_data_files_and_convert_to_cdf.cmake )

plato_functional_setup()
copy_test_utility_data_files_and_convert_to_cdf()
clang_tidy_setup()

add_subdirectory(./utilities)
add_subdirectory(./input_parser)
add_subdirectory(./linear_algebra)
add_subdirectory(./core)
add_subdirectory(./geometry)
add_subdirectory(./filter)
add_subdirectory(./criteria)
add_subdirectory(./rol_integration)
add_subdirectory(./process_manager)
add_subdirectory(./main)

if( UNIT_TESTING )
  add_subdirectory(./test_utilities)
  add_subdirectory(./integration_tests)
endif()
