#ifndef PLATO_PROCESS_MANAGER_EXTENSION_TEST_UTILITIES_NODALRESULTFILTERUTILITIES
#define PLATO_PROCESS_MANAGER_EXTENSION_TEST_UTILITIES_NODALRESULTFILTERUTILITIES

#include <filesystem>
#include <vector>

namespace plato::input_parser
{
class ParsedInput;
}

namespace plato::test_utilities
{
struct TestContext;
}

namespace plato::process_manager::extension::test_utilities
{
/// @brief Validates and runs the input in @a aParsedInput then checks that the output file generated by
/// nodal_result_filter exists and has the expected fields.
void run_and_check_nodal_filter_result(const input_parser::ParsedInput& aParsedInput,
                                       const std::vector<double>& aExpectedTimeSteps,
                                       const std::filesystem::path& aMeshPath,
                                       const plato::test_utilities::TestContext& aTestContext);
}  // namespace plato::process_manager::extension::test_utilities

#endif
