#include <gtest/gtest.h>

#include <stk_mesh/base/Part.hpp>

#include "plato/analysis/AnalysisDomainMesh.hpp"
#include "plato/mesh/Mesh.hpp"
#include "plato/test_utilities/TestContext.hpp"
#include "plato/third_party_integration/stk_io/CommandGenerator.hpp"
#include "plato/third_party_integration/stk_io/test_utilities/MeshFixtures.hpp"

namespace plato::mesh::unittest
{
namespace
{
using third_party_integration::stk_io::test_utilities::OneBlock3x1x1HexMesh;
using third_party_integration::stk_io::test_utilities::OneBlock3x1x1HexMeshWithNodeSets;
using third_party_integration::stk_io::test_utilities::TwoBlockMeshOnDisk;
using third_party_integration::stk_io::test_utilities::TwoDNonUniformHexMesh;
using third_party_integration::stk_io::test_utilities::TwoDThreeBlockMesh;

struct PublicPartVectorMixin : public Mesh
{
    PublicPartVectorMixin(Mesh aMesh) : Mesh{std::move(aMesh)} {}

    Mesh::PartReferenceVector publicFixedDomainBlocks() const { return Mesh::fixedDomainBlocks(); }

    Mesh::PartReferenceVector publicDesignDomainBlocks() const { return Mesh::designDomainBlocks(); }
};
}  // namespace

TEST_F(OneBlock3x1x1HexMesh, FilePath)
{
    const auto tMesh = Mesh{mMeshFilePath};
    EXPECT_EQ(tMesh.filePath(), mMeshFilePath);
}

TEST_F(OneBlock3x1x1HexMesh, NoFixedBlocks)
{
    const auto tMesh = Mesh{mMeshFilePath};
    EXPECT_TRUE(tMesh.fixedBlockOrdinals().empty());
}

TEST_F(OneBlock3x1x1HexMesh, FixedBlockOrdinals)
{
    const auto tMesh = Mesh{mMeshFilePath, {"block_1"}};

    // These Ordinals are essentially regression values, they are generated by stk
    const auto tExpectedBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{45u};
    EXPECT_EQ(tMesh.fixedBlockOrdinals(), tExpectedBlockOrdinals);
    EXPECT_TRUE(tMesh.designBlockOrdinals().empty());
}

TEST_F(TwoBlockMeshOnDisk, FixedBlockOrdinals)
{
    const auto tMesh = Mesh{mMeshFilePath, {"block_1", "block_2"}};

    const auto tExpectedBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{45u, 46u};
    EXPECT_EQ(tMesh.fixedBlockOrdinals(), tExpectedBlockOrdinals);
    EXPECT_TRUE(tMesh.designBlockOrdinals().empty());
}

TEST_F(TwoDNonUniformHexMesh, FixedBlockOrdinals)
{
    const auto tMesh = Mesh{mMeshFilePath, {"block_1"}};

    const auto tExpectedBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{20u};
    EXPECT_EQ(tMesh.fixedBlockOrdinals(), tExpectedBlockOrdinals);
    EXPECT_TRUE(tMesh.designBlockOrdinals().empty());
}

TEST_F(TwoDThreeBlockMesh, FixedBlockOrdinals)
{
    const auto tMesh = Mesh{mMeshFilePath, {"block_2", "block_3"}};

    const auto tExpectedBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{21u, 22u};
    EXPECT_EQ(tMesh.fixedBlockOrdinals(), tExpectedBlockOrdinals);
}

TEST_F(OneBlock3x1x1HexMesh, DesignBlockOrdinals)
{
    const auto tMesh = Mesh{mMeshFilePath};

    const auto tExpectedBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{45u};
    EXPECT_EQ(tMesh.designBlockOrdinals(), tExpectedBlockOrdinals);
    EXPECT_TRUE(tMesh.fixedBlockOrdinals().empty());
}

TEST_F(TwoBlockMeshOnDisk, DesignBlockOrdinals)
{
    const auto tMesh = Mesh{mMeshFilePath, {"block_2"}};

    const auto tExpectedBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{45u};
    EXPECT_EQ(tMesh.designBlockOrdinals(), tExpectedBlockOrdinals);
}

TEST_F(TwoDNonUniformHexMesh, DesignBlockOrdinals)
{
    const auto tMesh = Mesh{mMeshFilePath};

    const auto tExpectedBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{20u};
    EXPECT_EQ(tMesh.designBlockOrdinals(), tExpectedBlockOrdinals);
}

TEST_F(TwoDThreeBlockMesh, DesignBlockOrdinals)
{
    const auto tMesh = Mesh{mMeshFilePath, {"block_2", "block_3"}};

    const auto tExpectedBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{20u};
    EXPECT_EQ(tMesh.designBlockOrdinals(), tExpectedBlockOrdinals);
}

TEST_F(TwoDThreeBlockMesh, PartVectors)
{
    const auto tFixedBlockNames = std::set<std::string>{"block_2", "block_3"};
    const auto tMesh = Mesh{mMeshFilePath, tFixedBlockNames};

    const auto& tFixedBlockOrdinals = tMesh.fixedBlockOrdinals();
    ASSERT_EQ(tFixedBlockNames.size(), tFixedBlockOrdinals.size());

    const auto tFixedParts = PublicPartVectorMixin{tMesh}.publicFixedDomainBlocks();
    ASSERT_EQ(tFixedParts.size(), tFixedBlockOrdinals.size());
    EXPECT_EQ(tFixedParts.front().get().mesh_meta_data_ordinal(), tFixedBlockOrdinals.front());
    EXPECT_EQ(tFixedParts.back().get().mesh_meta_data_ordinal(), tFixedBlockOrdinals.back());

    const auto tDesignParts = PublicPartVectorMixin{tMesh}.publicDesignDomainBlocks();
    const auto& tDesignBlockOrdinals = tMesh.designBlockOrdinals();
    ASSERT_EQ(tDesignParts.size(), tDesignBlockOrdinals.size());
    EXPECT_EQ(tDesignParts.front().get().mesh_meta_data_ordinal(), tDesignBlockOrdinals.front());
}

TEST_F(TwoDThreeBlockMesh, ConstructionFromAnalysisDomainMesh)
{
    // Element-based densities
    const auto tBlock1ScalarField =
        analysis::AnalysisDomainMesh::ScalarFieldVector{{4, 0, 1.0}, {5, 1, 1.0}, {6, 2, 1.0}, {7, 3, 1.0}};
    const auto tBlock2ScalarField = analysis::AnalysisDomainMesh::ScalarFieldVector{{1, 4, 1.0}, {2, 5, 1.0}};
    const auto tBlock3ScalarField = analysis::AnalysisDomainMesh::ScalarFieldVector{{8, 6, 1.0}};

    const auto tTestFunction = [this](const Mesh& aMesh,
                                      const std::vector<Mesh::BlockOrdinalType>& aExpectedDesignBlockOrdinals,
                                      const std::vector<Mesh::BlockOrdinalType>& aExpectedFixedBlockOrdinals,
                                      const test_utilities::TestContext& aTestContext)
    {
        EXPECT_EQ(aMesh.filePath(), mMeshFilePath) << aTestContext;
        EXPECT_EQ(aMesh.designBlockOrdinals(), aExpectedDesignBlockOrdinals) << aTestContext;
        EXPECT_EQ(aMesh.fixedBlockOrdinals(), aExpectedFixedBlockOrdinals) << aTestContext;
    };

    const auto aAllFixedBlocksContext = TEST_CONTEXT("All fixed blocks");
    {
        const auto tMesh = Mesh{analysis::AnalysisDomainMesh{mMeshFilePath, {}}};
        const auto tExpectedDesignBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{};
        const auto tExpectedFixedBlockOrdinals =
            std::vector<Mesh::BlockOrdinalType>{mBlock1Ordinal, mBlock2Ordinal, mBlock3Ordinal};
        tTestFunction(tMesh, tExpectedDesignBlockOrdinals, tExpectedFixedBlockOrdinals, aAllFixedBlocksContext);
    }
    const auto aOneBlockContext = TEST_CONTEXT("One fixed block");
    {
        const auto tScalarField = analysis::AnalysisDomainMesh::BlockScalarField{{1, tBlock1ScalarField}};
        const auto tMesh = Mesh{analysis::AnalysisDomainMesh{mMeshFilePath, tScalarField}};
        const auto tExpectedDesignBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{mBlock1Ordinal};
        const auto tExpectedFixedBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{mBlock2Ordinal, mBlock3Ordinal};
        tTestFunction(tMesh, tExpectedDesignBlockOrdinals, tExpectedFixedBlockOrdinals, aOneBlockContext);
    }
    const auto aTwoBlockContext = TEST_CONTEXT("Two fixed blocks");
    {
        const auto tScalarField =
            analysis::AnalysisDomainMesh::BlockScalarField{{2, tBlock2ScalarField}, {3, tBlock3ScalarField}};
        const auto tMesh = Mesh{analysis::AnalysisDomainMesh{mMeshFilePath, tScalarField}};
        const auto tExpectedDesignBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{mBlock2Ordinal, mBlock3Ordinal};
        const auto tExpectedFixedBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{mBlock1Ordinal};
        tTestFunction(tMesh, tExpectedDesignBlockOrdinals, tExpectedFixedBlockOrdinals, aTwoBlockContext);
    }
    const auto aThreeBlockContext = TEST_CONTEXT("Three fixed blocks");
    {
        const auto tScalarField = analysis::AnalysisDomainMesh::BlockScalarField{
            {1, tBlock1ScalarField}, {2, tBlock2ScalarField}, {3, tBlock3ScalarField}};
        const auto tMesh = Mesh{analysis::AnalysisDomainMesh{mMeshFilePath, tScalarField}};
        const auto tExpectedDesignBlockOrdinals =
            std::vector<Mesh::BlockOrdinalType>{mBlock1Ordinal, mBlock2Ordinal, mBlock3Ordinal};
        const auto tExpectedFixedBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{};
        tTestFunction(tMesh, tExpectedDesignBlockOrdinals, tExpectedFixedBlockOrdinals, aThreeBlockContext);
    }
}

TEST_F(OneBlock3x1x1HexMeshWithNodeSets, ConstructionFromAnalysisDomainMesh)
{
    const auto tScalarField = analysis::AnalysisDomainMesh::ScalarFieldVector{{1, 0, 1.0}, {2, 1, 2.0}, {3, 2, 3.0}};
    constexpr auto tBlockID = 1;
    const auto tAnalysisDomainMesh = analysis::AnalysisDomainMesh{mMeshFilePath, {{tBlockID, tScalarField}}};

    {
        const auto tMesh = Mesh{mMeshFilePath};
        EXPECT_EQ(tMesh.designBlockOrdinals().size(), 1U);
        EXPECT_EQ(tMesh.fixedBlockOrdinals().size(), 0U);
    }
    {
        const auto tMesh = Mesh{tAnalysisDomainMesh};
        EXPECT_EQ(tMesh.designBlockOrdinals().size(), 1U);
        EXPECT_EQ(tMesh.fixedBlockOrdinals().size(), 0U);
    }
}

TEST_F(TwoDThreeBlockMesh, Valid)
{
    {
        const auto tMesh = Mesh{mMeshFilePath};
        EXPECT_TRUE(tMesh.valid());
    }
    {
        const auto tMesh = Mesh{analysis::AnalysisDomainMesh{mMeshFilePath, {}}};
        EXPECT_TRUE(tMesh.valid());
    }
}

TEST(Mesh, NonExistentMesh)
{
    const auto tBogusFilePath = std::filesystem::path{"bogus-file-path.e"};
    {
        const auto tMesh = Mesh{tBogusFilePath};
        EXPECT_FALSE(tMesh.valid());
    }
    {
        const auto tMesh = Mesh{analysis::AnalysisDomainMesh{tBogusFilePath, {}}};
        EXPECT_FALSE(tMesh.valid());
    }
}

}  // namespace plato::mesh::unittest
