#include <gtest/gtest.h>

#include <stk_mesh/base/Part.hpp>

#include "plato/mesh/Mesh.hpp"
#include "plato/third_party_integration/stk_io/test_utilities/Fixtures.hpp"

namespace plato::mesh::unittest
{
namespace
{
using third_party_integration::stk_io::test_utilities::OneBlock3x1x1HexMesh;
using third_party_integration::stk_io::test_utilities::TwoBlockMeshOnDisk;
using third_party_integration::stk_io::test_utilities::TwoDNonUniformHexMesh;
using third_party_integration::stk_io::test_utilities::TwoDThreeBlockMesh;

struct PublicPartVectorMixin : public Mesh
{
    PublicPartVectorMixin(Mesh aMesh) : Mesh{std::move(aMesh)} {}

    Mesh::PartReferenceVector publicFixedDomainBlocks() const { return Mesh::fixedDomainBlocks(); }

    Mesh::PartReferenceVector publicDesignDomainBlocks() const { return Mesh::designDomainBlocks(); }
};
}  // namespace

TEST_F(OneBlock3x1x1HexMesh, FilePath)
{
    const auto tMesh = Mesh{mMeshFilePath};
    EXPECT_EQ(tMesh.filePath(), mMeshFilePath);
}

TEST_F(OneBlock3x1x1HexMesh, NoFixedBlocks)
{
    const auto tMesh = Mesh{mMeshFilePath};
    EXPECT_TRUE(tMesh.fixedBlockOrdinals().empty());
}

TEST_F(OneBlock3x1x1HexMesh, FixedBlockOrdinals)
{
    const auto tMesh = Mesh{mMeshFilePath, {"block_1"}};

    // These Ordinals are essentially regression values, they are generated by stk
    const auto tExpectedBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{40u};
    EXPECT_EQ(tMesh.fixedBlockOrdinals(), tExpectedBlockOrdinals);
    EXPECT_TRUE(tMesh.designBlockOrdinals().empty());
}

TEST_F(TwoBlockMeshOnDisk, FixedBlockOrdinals)
{
    const auto tMesh = Mesh{mMeshFilePath, {"block_1", "block_2"}};

    const auto tExpectedBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{40u, 41u};
    EXPECT_EQ(tMesh.fixedBlockOrdinals(), tExpectedBlockOrdinals);
    EXPECT_TRUE(tMesh.designBlockOrdinals().empty());
}

TEST_F(TwoDNonUniformHexMesh, FixedBlockOrdinals)
{
    const auto tMesh = Mesh{mMeshFilePath, {"block_1"}};

    const auto tExpectedBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{20u};
    EXPECT_EQ(tMesh.fixedBlockOrdinals(), tExpectedBlockOrdinals);
    EXPECT_TRUE(tMesh.designBlockOrdinals().empty());
}

TEST_F(TwoDThreeBlockMesh, FixedBlockOrdinals)
{
    const auto tMesh = Mesh{mMeshFilePath, {"block_2", "block_3"}};

    const auto tExpectedBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{21u, 22u};
    EXPECT_EQ(tMesh.fixedBlockOrdinals(), tExpectedBlockOrdinals);
}

TEST_F(OneBlock3x1x1HexMesh, DesignBlockOrdinals)
{
    const auto tMesh = Mesh{mMeshFilePath};

    const auto tExpectedBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{40u};
    EXPECT_EQ(tMesh.designBlockOrdinals(), tExpectedBlockOrdinals);
    EXPECT_TRUE(tMesh.fixedBlockOrdinals().empty());
}

TEST_F(TwoBlockMeshOnDisk, DesignBlockOrdinals)
{
    const auto tMesh = Mesh{mMeshFilePath, {"block_2"}};

    const auto tExpectedBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{40u};
    EXPECT_EQ(tMesh.designBlockOrdinals(), tExpectedBlockOrdinals);
}

TEST_F(TwoDNonUniformHexMesh, DesignBlockOrdinals)
{
    const auto tMesh = Mesh{mMeshFilePath};

    const auto tExpectedBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{20u};
    EXPECT_EQ(tMesh.designBlockOrdinals(), tExpectedBlockOrdinals);
}

TEST_F(TwoDThreeBlockMesh, DesignBlockOrdinals)
{
    const auto tMesh = Mesh{mMeshFilePath, {"block_2", "block_3"}};

    const auto tExpectedBlockOrdinals = std::vector<Mesh::BlockOrdinalType>{20u};
    EXPECT_EQ(tMesh.designBlockOrdinals(), tExpectedBlockOrdinals);
}

TEST_F(TwoDThreeBlockMesh, PartVectors)
{
    const auto tFixedBlockNames = std::vector<std::string>{"block_2", "block_3"};
    const auto tMesh = Mesh{mMeshFilePath, tFixedBlockNames};

    const auto& tFixedBlockOrdinals = tMesh.fixedBlockOrdinals();
    ASSERT_EQ(tFixedBlockNames.size(), tFixedBlockOrdinals.size());

    const auto tFixedParts = PublicPartVectorMixin{tMesh}.publicFixedDomainBlocks();
    ASSERT_EQ(tFixedParts.size(), tFixedBlockOrdinals.size());
    EXPECT_EQ(tFixedParts.front().get().mesh_meta_data_ordinal(), tFixedBlockOrdinals.front());
    EXPECT_EQ(tFixedParts.back().get().mesh_meta_data_ordinal(), tFixedBlockOrdinals.back());

    const auto tDesignParts = PublicPartVectorMixin{tMesh}.publicDesignDomainBlocks();
    const auto& tDesignBlockOrdinals = tMesh.designBlockOrdinals();
    ASSERT_EQ(tDesignParts.size(), tDesignBlockOrdinals.size());
    EXPECT_EQ(tDesignParts.front().get().mesh_meta_data_ordinal(), tDesignBlockOrdinals.front());
}

}  // namespace plato::mesh::unittest
